# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Brightcove Beacon Documentation
email: training@brightcove.com
description: >- # this means to ignore newlines until "baseurl:"
  Brightcove Beacon provides video providers the environment for their customers to view videos without having a cable provider subscription.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://brightcovelearning.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: minima

product: Brightcove Beacon
color: rgb(51, 51, 51)
defaults:
  - 
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
# you should have a collection corresponding to each folder of docs
collections:
  getting_started:
    output: true
    order:
      - index.html
    title: Getting Started
    relative_directory: /get-started
    docs:
      home:
        relative_path: /get-started/index.html
  video_cloud_sync:
    output: true
    order:
      - index.html
    title: Video Cloud Sync
    relative_directory: /video-cloud-sync
    docs:
      home:
        title: Video Cloud Sync Home
        relative_path: /video-cloud-sync/index.html
  admin_console:
    output: true
    order:
      - index.html
    title: Admin Console
    relative_directory: /admin-console
    docs:
      home:
        title: Admin Console Home
        relative_path: /admin-console/index.html
  submitting_apps:
    output: true
    order:
      - index.html
    title: Submitting Apps
    relative_directory: /submitting_apps
    docs:
      home:
        title: Submitting Apps Home
        relative_path: /submitting_apps/index.html
  references:
    output: true
    order:
      - index.html
      - product-updates.html
      - known-issues.html
    title: References
    relative_directory: /references
    docs:
      home:
        title: References Home
        relative_path: /references/index.html
      Product Updates:
        title: Product Updates
        relative_path: /references/product-updates.html
      known_issues:
        title: Known Issues
        relative_path: /references/known-issues.html


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
